### ISSUE TITLE
Token invalid 

### ISSUE THREAD

**Issue by mike391** [loganmarchione/docker-speedtest-influxdbv2#5]
https://github.com/loganmarchione/docker-speedtest-influxdbv2/blob/a57d1e043354af6905079c89d9c0649558e837d8/speedtest.py#L130

This line needs to accept an actual token from influxdb V2.  User:Password is not valid any longer as a token replacement.

**Comment by loganmarchione** [comment]
@mike391 thanks for this issue. Long story, but I messed up and was under the impression [from this](https://docs.influxdata.com/influxdb/v1.8/tools/api/#apiv2query-http-endpoint) that v2 would accept username/passwords, but I guess that's only for v1.8 using the v2 API. However, right now, I am currently still on Influx v1.8, so I don't have a v2 database to test against. I plan on migrating a few things to v2, at which point I'll update this container, but I don't have a timeline for you right now.

My plan will be:

- Unarchive [this version](https://github.com/loganmarchione/docker-speedtest-influxdb), which works with v1.8 and lower
- Backport fixes from this python script to the older version
- Update this script to support tokens properly
- Bump the version from 0.0.14 to 1.0.0, since I'll be breaking API capability

**Comment by loganmarchione** [comment]
I added a [project](https://github.com/loganmarchione/docker-speedtest-influxdbv2/projects/1) for this

**Comment by loganmarchione** [comment]
@mike391 Please test the new tag 1.0.0 and let me know how this works.
https://hub.docker.com/layers/loganmarchione/docker-speedtest-influxdbv2/1.0.0/images/sha256-37ff4d41c28a92f8477121da548e23e6c81f1fc2c5dfae2625db72599780b6fa?context=explore 

I'm not using a v2 database in my homelab, but running a test on my local machine, this new 1.0.0 tag works. See the README for what variables to pass.  
https://github.com/loganmarchione/docker-speedtest-influxdbv2/blob/master/README.md

**Comment by loganmarchione** [comment]
Someone in #7 said InfluxDB v2 is working, so I'm closing this.
