### ISSUE TITLE
Stopped Looping

### ISSUE THREAD

**Issue by GazaShaggy** [loganmarchione/docker-speedtest-influxdbv2#8]
Hello again.

This has happened twice now runs fine for about 6 days then for some reason stops.
Docker logs show everything fine apart from missing the last "Sleeping for **** seconds"

I've been reading and thought maybe changing it over to a cron job might fix this (and will always run at a specific time, now moves forward about 20-30 seconds each time) if that's not to hard to do?

**Comment by loganmarchione** [comment]
I haven't experienced this personally. But just thinking out loud, I guess my options are either:

1. Run the script at every X interval (e.g., run every 300 seconds)
1. Run the script at a specific repeating time (e.g., run every day at 1pm)

For option 1...
Right now I'm using `time.sleep()` which is admittedly basic. I could replace `time.sleep()` with [threading](https://docs.python.org/3/library/threading.html#timer-objects) or [sched](https://docs.python.org/3/library/sched.html) or [schedule](https://schedule.readthedocs.io/en/stable/) to see if you have better results.

For option 2...
I could also use [schedule](https://schedule.readthedocs.io/en/stable/), but having the user specify an interval between runs (e.g, 300 seconds) is easier than doing the "crontab" format. For example, saying "every day at 1pm" or "every 2 hours" or "every hour at minute 01". The interval (X) and the unit of time (e.g., day vs hour vs minute) changes. It's too much to account for. 

The 20-30 seconds time skip is due to how long it takes the loop to run (i.e., the database check, the speedtest itself, then writing to the database). I'd have to time each run and then subtract that time from the interval (X).

**Comment by ghost** [comment]
I am a fan of number 2. I am starting to see with keeping the default sleep time that the speed test will run at different times through the day. If a test take a little bit longer to come back and then go to sleep I can start pushing back the time I run speed test minute by minute. I would really like the option to run the speed test everyday at like :35 after the hour. I have no problem opening a feature if that is the route but thought I would give a +1 since this is still out there. Thanks

**Comment by nodiaque** [comment]
you could make a cron job that start the test at x then kill the process after 5 min

**Comment by loganmarchione** [comment]
Telegraf now has an official[ Internet Speed Monitor plugin](https://github.com/influxdata/telegraf/tree/master/plugins/inputs/internet_speed). I recommend using that instead.

This project is being archived and the container image will be removed from Docker Hub. You can still build the container image from source if you'd like.
